IntroMonitoringEnginnering/Controllers/CategoryController.cs
using IntroMonitoringEngineering.Interfaces;
using IntroMonitoringEngineering.ViewModel.Category;
using IntroMonitoringEnginnering.Models;
using Microsoft.AspNetCore.Mvc;

namespace IntroMonitoringEngineering.Controllers
{
    public class CategoryController : Controller
    {

        private readonly ICategoryService _categoryService;
        private readonly IDetailService _informationService;
        private readonly IEmailService _emailService;

        public CategoryController(ICategoryService categoryService, IDetailService informationService, IEmailService emailService)
        {
            _categoryService = categoryService;
            _informationService = informationService;
            _emailService = emailService;
        }



        public async Task<IActionResult> GetAllCategory()
        {
            var item = await _categoryService.GetAllCategoriesAsync();
            return View(item);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View(); 
        }




        [HttpPost]
        public async Task<IActionResult> Create(CategoryCreate categoryCreate)
        {
            if (ModelState.IsValid)
            {

                var category = new Category
                {
                    Title = categoryCreate.Title
                };

                await _categoryService.AddCategoryAsync(category);
                return RedirectToAction("Index", "Context");
            }

            return View(categoryCreate);
        }


        public async Task<IActionResult> Edit(int id)
        {
            var category = await _categoryService.GetCategoryByIdAsync(id);
            return View(category);
        }


       

        [HttpPost]
        public async Task<IActionResult> Edit(int id, CategoryEdit model)
        {
            if (ModelState.IsValid)
            {
                var category = await _categoryService.GetCategoryByIdAsync(id);
                if (category == null)
                {
                    return NotFound();
                }

                category.Title = model.Title;
                await _categoryService.UpdateCategoryAsync(category);
                return RedirectToAction("Index", "Context");
            }

            ViewBag.CategoryId = id;
            return View(model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _categoryService.DeleteCategoryAsync(id);
            return RedirectToAction("Index","Context"); 
        }









    }
}

IntroMonitoringEnginnering/Controllers/ContextController.cs
using IntroMonitoringEngineering.Data;
using IntroMonitoringEngineering.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace IntroMonitoringEngineering.Controllers
{
    public class ContextController : Controller
    {

        private readonly ICategoryService _categoryService;
        private readonly IDetailService _informationService;
        private readonly AppDbContext _context;
        private readonly IImageService _imageService;


        public ContextController(ICategoryService categoryService, IDetailService informationService, AppDbContext context, IImageService imageService = null)
        {
            _categoryService = categoryService;
            _informationService = informationService;
            _context = context;
            _imageService = imageService;
        }



        public async Task<IActionResult> Index(int? categoryId)
        {
            var categories = await _categoryService.GetAllCategoriesAsync();
            ViewBag.Categories = categories;

            var img = await _imageService.GetAllImage();
            ViewBag.Images = img;

            if (true)
            {
                ViewBag.Images = img.ToList();
            }
            else
            {
                ViewBag.Images = img;
            }

            var item = await _informationService.GetAllInformationAsync();
         

            if (categoryId.HasValue)
            {
                var selectedCategory = await _categoryService.GetCategoryByIdAsync(categoryId.Value);
                ViewBag.SelectedCategory = selectedCategory;

                var categoryInformation = await _informationService.GetInformationByCategoryIdAsync(categoryId.Value);
                ViewBag.Information = categoryInformation;
            }

            return View(item);
        }


     




        public async Task<IActionResult> About()
        {
            var categories = await _categoryService.GetAllCategoriesAsync();
            ViewBag.Categories = categories;

            return View();

        }







    }
}

IntroMonitoringEnginnering/Controllers/DetailController.cs
using IntroMonitoringEngineering.Data;
using IntroMonitoringEngineering.Interfaces;
using IntroMonitoringEngineering.Models;
using IntroMonitoringEngineering.Services;
using IntroMonitoringEngineering.ViewModel.Detail;
using IntroMonitoringEnginnering.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace IntroMonitoringEngineering.Controllers
{
    public class DetailController : Controller
    {



        private readonly ICategoryService _categoryService;
        private readonly IDetailService _informationService;
        private readonly IImageService _imageService;
        private readonly AppDbContext _context;

        public DetailController(IDetailService informationService, ICategoryService categoryService, AppDbContext context, IImageService imageService)
        {
            _informationService = informationService;
            _categoryService = categoryService;
            _context = context;
            _imageService = imageService;
        }


        public async Task<IActionResult> Search(string searchQuery)
        {
            var details = await _informationService.GetAllInformationAsync(searchQuery);
            return View(details);
        }



        public async Task<IActionResult> Create()
        {
        
            var categories = await _categoryService.GetAllCategoriesAsync();

            var viewModel = new DetailCreateViewModel
            {
                Categories = categories?.Select(c => new SelectListItem
                {
                    Text = c.Title, 
                    Value = c.Id.ToString() 
                }).ToList() ?? new List<SelectListItem>() 
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(DetailCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
             
                var detail = new Detail
                {
                    Description = model.Description,
                    CategoryId = model.CategoryId
                };

             
                await _informationService.AddInformationAsync(detail);

                if (model.Images != null && model.Images.Count > 0)
                {
                    foreach (var imageFile in model.Images)
                    {
                        if (imageFile.Length > 0)
                        {
              
                            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", imageFile.FileName);

                            using (var stream = new FileStream(filePath, FileMode.Create))
                            {
                                await imageFile.CopyToAsync(stream);
                            }

                         
                            var image = new ImageUrl
                            {
                                Url = "/images/" + imageFile.FileName, 
                                AltText = "Image for " + detail.Description,
                                DetailId = detail.Id
                            };

                            await _informationService.AddImageAsync(image);
                        }
                    }
                }
            }

            return View(model);
        }




        public async Task<IActionResult> DeleteInformation(int informationId, int categoryId)
        {
            await _informationService.DeleteInformationAsync(informationId);
            return RedirectToAction("Index", "Context", new { categoryId = categoryId });
        }







        [HttpGet("edit/{id}")]
        public async Task<IActionResult> EditDescription(int id)
        {
            var detail = await _informationService.GetDetailByIdAsync(id);
            if (detail == null)
            {
                return NotFound();
            }

            var viewModel = new DetailViewModel
            {
                Id = detail.Id,
                Description = detail.Description
            };

            return View("EditDescription", viewModel);
        }





        [HttpPost("edit/{id}")]
        public async Task<IActionResult> UpdateDescription(int id, DetailViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("UpdateDescription", model);
            }

            var detail = await _informationService.GetDetailByIdAsync(id);
            if (detail == null)
            {
                return NotFound();
            }

            detail.Description = model.Description;

            var updated = await _informationService.UpdateDetailAsync(detail);
            if (!updated)
            {
                ModelState.AddModelError("", "Failed to update the detail.");
                return View("UpdateDescription", model);
            }

            return RedirectToAction("Index", "Context");
            
        }
















    }


}

IntroMonitoringEnginnering/Controllers/ImageController.cs
using IntroMonitoringEngineering.Data;
using IntroMonitoringEngineering.Interfaces;
using IntroMonitoringEngineering.ViewModel.Image;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IntroMonitoringEngineering.Controllers
{
    public class ImageController : Controller
    {


        private readonly AppDbContext _context;
        private readonly IImageService _imageService;


        public ImageController(AppDbContext context, IImageService imageService)
        {
            _context = context;
            _imageService = imageService;
        }


        [HttpGet]
        public async Task<IActionResult> EditImage(int id)
        {
            var image = await _context.Images.FirstOrDefaultAsync(i => i.Id == id);

            if (image == null)
            {
                return NotFound();
            }

            var model = new EditImageViewModel
            {
                Id = image.Id,
                AltText = image.AltText,
                CurrentImageUrl = image.Url,
                DetailId = image.DetailId
            };

            return View(model);
        }




        [HttpPost]
        public async Task<IActionResult> EditImage(int id, IFormFile newImage, string newAltText)
        {
            var categoryId = await _imageService.EditImageAsync(id, newImage, newAltText);

            if (categoryId == null)
            {
                return NotFound("Image or associated category not found.");
            }
            return RedirectToAction("Index", "Context", new { categoryId = categoryId });
        }




        [HttpGet]
        public async Task<IActionResult> DeleteImage(int id, int categoryId)
        {
            var result = await _imageService.DeleteImageAsync(id);
            if (result)
            {
                return RedirectToAction("Index", "Context", new { categoryId = categoryId });
            }

            return NotFound();
        }






    }
}

IntroMonitoringEnginnering/Views/Context/About.cshtml
<div class="container description-container p-4 auth">
    <p class="text-light">
        Global TV არის ქართული საკაბელო და სატელიტური ტელევიზიის ოპერატორი, რომელიც მომხმარებლებს სთავაზობს მრავალფეროვან არხებსა და მომსახურებებს. მისი მიზანია მაღალი ხარისხის სერვისების მიწოდება როგორც სატელიტური ტელევიზიის, ისე ციფრული კონტენტის სფეროში.

        Global TV-ის ისტორია და განვითარება:
        დაარსება:

        კომპანია დაარსდა 2000-იანი წლების დასაწყისში და სწრაფად მოიპოვა პოპულარობა სატელიტური ტელევიზიის ბაზარზე.
        მთავარი სერვისები:

        სატელიტური ტელევიზია: ქართული და საერთაშორისო სატელევიზიო არხების ტრანსლაცია.
        ინტერნეტ მომსახურება: კომპანია ასევე სთავაზობს მაღალი სიჩქარის ინტერნეტს.
        HD და ციფრული კონტენტი: მომხმარებლებს აქვთ წვდომა მაღალი გარჩევადობის არხებსა და ფილმებზე.
        ფართო გაშუქება:

        Global TV საქართველოს თითქმის ყველა რეგიონში ახორციელებს მომსახურებას, რაც უზრუნველყოფს ქვეყნის მასშტაბით ტელევიზიის ხელმისაწვდომობას.
        მახასიათებლები და უპირატესობები:
        არხების მრავალფეროვნება:
        Global TV მოიცავს ქართულ, საერთაშორისო, სპორტულ, საბავშვო, გასართობ და დოკუმენტურ არხებს.

        ინოვაციური ტექნოლოგიები:
        კომპანიამ დანერგა თანამედროვე სატელიტური სერვისები, რაც საშუალებას აძლევს მომხმარებლებს მიიღონ ხარისხიანი სიგნალი საქართველოს რთულ გეოგრაფიულ პირობებში.

        მომხმარებლის მომსახურება:
        Global TV განსაკუთრებულ ყურადღებას აქცევს მომხმარებელთა კმაყოფილებას და ტექნიკურ მხარდაჭერას.

        საზოგადოებრივი და პოლიტიკური გავლენა:
        Global TV აქტიურად მონაწილეობდა ინფორმაციის გავრცელებაში, განსაკუთრებით რეგიონებში, სადაც ტელევიზიის მიღების სხვა საშუალებები არ იყო ხელმისაწვდომი.
        კომპანიის განვითარების გარკვეულ ეტაპზე, ის ასოცირდებოდა პოლიტიკურ პროცესებთან, თუმცა დღესდღეობით ფოკუსირებულია კომერციულ საქმიანობაზე.
        დასკვნა:
        Global TV ერთ-ერთი პირველი და უმნიშვნელოვანესი კომპანიაა საქართველოს სატელიტური ტელევიზიის ბაზარზე. მისი სტრატეგიული მიზანი ქართული ოჯახებისთვის ხელმისაწვდომი, მაღალი ხარისხის სატელევიზიო სერვისის მიწოდებაა.
    </p>
</div>

IntroMonitoringEnginnering/Views/Context/Index.cshtml
@using IntroMonitoringEngineering.Models
@using Microsoft.VisualBasic
@model List<Detail>

@{
    var categories = ViewBag.Categories as List<Category>;
    var selectedCategory = ViewBag.SelectedCategory as Category;
    var categoryInformation = ViewBag.Information as List<Detail>;
    var imgs = ViewBag.Images as List<ImageUrl>;
    
}




<div class="container">




    <div class="row ">
        <div class="col-3 category-container m-auto @((selectedCategory == null) ? "d-none" : "")" id="categoryContainer">

            @if (categories != null && categories.Any())
            {
                foreach (var category in categories)
                {

                    <div class="d-flex position-relative">

                        <div class="nav-item">

                            <a class="nav-link text-light" href="@Url.Action("Index", "Context", new { categoryId = category.Id })">
                                @category.Title
                            </a>

                        </div>

                        <div class="d-flex position-absolute category-icon">
                            @if (User.IsInRole("Admin"))
                            {
                                <a class="nav-link text-dark" href="@Url.Action("Edit", "Category", new { id = category.Id })" class="btn btn-warning">
                                    <i class="fa-regular fa-pen-to-square edit"></i>
                                </a>

                                <a class="nav-link text-dark" href="@Url.Action("Delete", "Category", new { id = category.Id })" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this category?');">
                                    <i class="fa-solid fa-trash-can remove"></i>
                                </a>
                            }
                        </div>

                    </div>
                }
            }
            else
            {
                <p class="text-danger">No categories available.</p>
            }

        </div>




        <div class="col position-relative">
            @if (categoryInformation != null && categoryInformation.Any(info => info.Image != null && info.Image.Any()))
            {
                <div class="d-flex justify-content-center description-images">
                    @foreach (var info in categoryInformation)
                    {
                        if (info.Image != null && info.Image.Any())
                        {
                            foreach (var image in info.Image)
                            {
                                <div>
                                    <img class="content-img" src="@Url.Content(image.Url)" alt="@image.AltText" width="100" height="100" style="margin: 5px;" onmouseover="toggleImageSize(this)" onmouseout="resetImageSize(this)" />

                                    <div>
                                        @if (User.IsInRole("Admin"))
                                        {
                                            <a class="text-decoration-none" href="@Url.Action("EditImage", "Image", new { id = image.Id })">
                                                <i class="fa-regular fa-pen-to-square edit me-3"></i>
                                            </a>

                                            <a class="text-decoration-none" href="@Url.Action("DeleteImage", "Image", new { id = image.Id, categoryId = selectedCategory.Id })" onclick="return confirm('Are you sure you want to delete this image?');">
                                                <i class="fa-solid fa-trash-can remove"></i>
                                            </a>
                                        }
                                    </div>
                                </div>
                            }
                        }
                    }
                </div>
            }


            @if (selectedCategory != null && categoryInformation != null && categoryInformation.Any())
            {
                <div class="row description-container m-3">
                    @foreach (var info in categoryInformation)
                    {
                        @if (info.Image != null && info.Image.Any())
                        {
                            foreach (var image in info.Image)
                            {
                                @if (!string.IsNullOrWhiteSpace(info.Description))
                                {
                                    <div class="description-text">
                                        <p class="text-light">
                                            @info.Description
                                  
                                        </p>
                                    </div>

                                    @if (User.IsInRole("Admin"))
                                    {
                                       
                                        <div class="d-flex">
                                            <a class="me-3" asp-controller="Detail" asp-action="EditDescription" asp-route-id="@info.Id">
                                                <i class="fa-regular fa-pen-to-square edit ms-3 me-3"></i>
                                            </a>
                                            <a href="@Url.Action("DeleteInformation", "Detail", new { informationId = info.Id, categoryId = selectedCategory.Id })" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this information?');">
                                                <i class="fa-solid fa-trash"></i>
                                            </a>
                                        </div>
                                    }


                                }
                            }
                        }
                        else
                        {
                            <span class="text-danger">No images available.</span>
                        }

                      
                    }
                </div>

            }
           


        </div>

    </div>

   

</div>









<script>
        document.addEventListener('DOMContentLoaded', function () {
      function toggleContainer() {
        const categoryContainer = document.querySelector('.category-container');

        if (!categoryContainer) {
          console.error("No element with class '.category-container' found.");
          return;
        }

        if (window.innerWidth >= 700) {
    
          if (categoryContainer.style.display === 'none') {
            categoryContainer.style.display = 'block';
          }
        } else {
   
          categoryContainer.style.display = 'none';
        }
      }


      toggleContainer();


      window.addEventListener('resize', toggleContainer);
    });

</script>